swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(document.domain)//
info:
  version: "0.0.1"
  title: Example Title
  description: <img src=x onerror="alert('all your base are belong to us')">
paths:
  /:
    get:
      responses:
        200:
          description: Successful respons
